config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "cocktails#index"
  resources :cocktails do
    resources :doses, only: [ :new, :create ]
    resources :reviews, only: [ :new, :create ]
    resources :cocktail_tags, only: [ :new, :create ]
  end
  resources :doses, only: [ :index, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :cocktail_tags, dependent: :destroy
  has_many :tags, through: :cocktail_tags
  has_many :cocktails, through: :cocktail_tags
  validates :name, presence: true, uniqueness: true
  mount_uploader :photo, PhotoUploader
end

app/models/cocktail_tag.rb
class CocktailTag < ApplicationRecord
  belongs_to :cocktail
  belongs_to :tag
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail_id, presence: true
  validates :ingredient_id, presence: true
  validates_uniqueness_of :cocktail_id, :scope => [:ingredient_id]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :cocktail_tags, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktail_tags_controller.rb
class CocktailTagsController < ApplicationController
    def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @cocktail_tag = CocktailTag.new
  end

  def create
    @tags = Tag.where(id: params[:cocktail_tag][:tag])
    @cocktail = Cocktail.find(params[:cocktail_id])
    @tags.each do |tag|
      CocktailTag.create(cocktail: @cocktail, tag: tag)
    end
    if @tags.empty?
      render :new
    else
      redirect_to cocktails_path
    end
  end

  private

  def cocktail_tag_params
    params.require(:cocktail_tag).permit(:tag_id)
  end
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    if params[:query]
      @cocktails = Cocktail.where("name LIKE '%#{params[:query]}%'")
    else
      @cocktails = Cocktail.all
    end
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.create!(cocktail_params)
    redirect_to cocktails_path
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(cocktail_params)
    redirect_to cocktail_path(@cocktail)
  end
end

private

def cocktail_params
  params.require(:cocktail).permit(:name, :picture, :photo)
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = Cocktail.find(params[:cocktail_id])
    @dose.save!
    redirect_to cocktail_path(@dose.cocktail)
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktails_path
  end

  def index
    @doses = Dose.all
  end
end

private

def dose_params
  params.require(:dose).permit(:description, :ingredient_id, :cocktail_id)
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
   def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.cocktail = Cocktail.find(params[:cocktail_id])
    @review.save!
    redirect_to cocktail_path(@review.cocktail)
  end

  private

  def review_params
    params.require(:review).permit(:content, :cocktail_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktail_tags_helper.rb
module CocktailTagsHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktail_tags/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>Add a new tag</h1>
      <%= simple_form_for [ @cocktail, @cocktail_tag ] do |f| %>
        <%= f.input :tag, collection: Tag.all, input_html: { multiple: true, class: "select2" } %>
        <%= f.submit class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/edit.html.erb
<div class="container">
  <h1>Edit cocktail</h1>
  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.input :picture %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.submit "Edit cocktail", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/cocktails/index.html.erb
<div class="wrapper wrapper-index " style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://images.unsplash.com/photo-1530064161350-7824b8cdeee9?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=22e0769dd17e74e43f6811717147f96d&auto=format&fit=crop&w=1350&q=80')">
  <div class="container typed">
    <h1 id="banner-typed-text"></h1>
  </div>
  <%= link_to "New cocktail", new_cocktail_path, class: "btn btn-success btn-banner" %>
</div>
<div class="wrapper-title">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
          <% @cocktails.each do |cocktail| %>
            <div class="col-xs-12 col-md-6">
              <div class="card">
                  <div class="flat-card-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cocktail.photo %>')">
                    <div class="text"><%= link_to "#{cocktail.name}", cocktail_path(cocktail) %></div>
                  </div>
                <div class="tags">
                    <%= link_to new_cocktail_cocktail_tag_path(cocktail) do %>
                      <i class="fa fa-plus"></i>
                    <% end %>
                  <ul class="list-inline">
                    <% cocktail.tags.each do |tag| %>
                      <li class="list-inline-item" ><%= tag.name %></li>
                    <% end %>
                  </ul>
                </div>
              </div>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <h1>Create a new cocktail</h1>
  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.input :picture %>
    <%= f.input :photo %>
    <%= f.submit "add a cocktail", class: "btn btn-success" %>
  <% end %>
</div>

app/views/cocktails/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= @cocktail.photo %>');")">
    <%= link_to "Edit cocktail", edit_cocktail_path(@cocktail), class: "btn btn-success btn-custo" %>
    <h1>Cocktail: <%= @cocktail.name %></h1></br>
</div>
<div class="wrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-6">
        <h2>Doses</h2>
        <ul>
         <% @cocktail.doses.each do |dose| %>
          <li><%= "#{dose.ingredient.name.upcase}: #{dose.description} " %> <%= link_to dose_path(dose), method: :delete do %>
            <i class="fas fa-trash-alt"></i>
          <% end %></li>
         <% end %>
        </ul>
      </div>
      <div class="col-xs-12 col-md-6">
        <%= render "doses/form" %>
      </div>
    </div>
    <div class="review">
      <%= render "reviews/form" %>
      <h2>Reviews:</h2>
      <ul>
       <% @cocktail.reviews.each do |review| %>
        <li><strong><%= "#{review.created_at.strftime("%F %T")}" %></strong> <%= "- #{review.content}" %></li>
       <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/doses/_form.html.erb
  <h2>New dose</h2>
  <%= simple_form_for [@cocktail, Dose.new] do |f| %>
    <%= f.input :description %>
    <%= f.association :ingredient %>
    <%= f.submit "add a dose", class: "btn btn-success" %>
  <% end %>

app/views/doses/index.html.erb
<div class="container">
  <h1>All doses</h1>
  <ul>
    <% @doses.each do |dose| %>
        <li><%= "#{dose.id}. #{dose.description}" %></li>
    <% end %>
  </ul>
</div>

app/views/doses/new.html.erb
<div class="container">
  <h1>Create a new dose</h1>
  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.input :description %>
    <%= f.association :ingredient %>
    <%= f.submit "add a dose", class: "btn btn-success" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar-wagon">
      <%= link_to "Soirée cocktail.com", cocktails_path %>
      <div class="form-flex">
        <form action="/cocktails" method="get" class="form-inline">
          <input type="text" name="query" placeholder="search" class="form-control">
          <input type="submit" class= "btn btn-navbar" >
        </form>
      </div>
    </div>
    <%= yield %>
     <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
     <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>

app/views/reviews/_form.html.erb
  <h2>New review</h2>
  <%= simple_form_for [@cocktail, Review.new] do |f| %>
    <%= f.input :content, as: :text %>
    <%= f.submit "add a review", class: "btn btn-success" %>
  <% end %>